In [ ]:
# Data science
#Problem => Data acquire => Data pre-process => data storage =>
# Data Preparation => Data analysis => Data visualize
# ML and algorithm( chatbot, open ai service , Open CV ,NLP) => Data report

# Python => libraries => Pandas and numpy
#numpy => numerical python
# data prepare in form of number
#scientific library => data in form of nd array
# [1,2,3,4]

#[ [1,2],
#  [3,4]]

In [ ]:
mylist=[10,20,30]
mylist+5

TypeError: can only concatenate list (not "int") to list

In [ ]:
mylist=[10,20,30,"abc"]
mylist+5

In [ ]:
import numpy as np
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
np.arange(7)
type(np.arange(7))

numpy.ndarray

In [ ]:
import numpy as np
arr1=np.arange(7)
arr1

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.ndarray(3)

array([0. , 0.5, 1. ])

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
arr1=np.array([1,2,3,4])
arr1.size

4

In [ ]:
arr1=np.array([[1,2],[2,3],[5,6]])
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)

6
(3, 2)
int64


In [ ]:
arr2=np.ndarray(3)
arr2.shape

(3,)

In [ ]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr3=np.arange(9)
arr3.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
b=a.transpose()
print(b)

[[1 3]
 [2 4]]


In [ ]:
arr1=np.array([[[1,2.0],[2,3],[5,6]]])
print(arr1.ndim)
print(arr1.shape)

3
(1, 3, 2)


In [ ]:
# numpy
# string => conert => int
#pandas : powerful => data transform , clean , prepare
# Series : 1D array
# Dataframe : collection of series tabular format for your data
import pandas as pd
print(pd.DataFrame([10,2,34,4]))
print("""
""")
print(pd.Series([10,2,34,4]))


    0
0  10
1   2
2  34
3   4


0    10
1     2
2    34
3     4
dtype: int64


In [ ]:
import pandas
series1 = pandas.Series([10,2,34,4])
series1.values

array([10,  2, 34,  4])

In [ ]:
series1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
series1.index
print(series1[1])

2


In [ ]:
import pandas
series1 = pandas.Series([10,2,34,4])
series1[0] = 90 # update
series1[5]=1000 # insert
print(series1)
print("""
""")
print(series1.max())
print(series1.min())
print(series1.idxmax())
print(series1.idxmin())

0      90
1       2
2      34
3       4
5    1000
dtype: int64


1000
2
5
1


In [6]:
import pandas
series1 = pandas.Series([10,2,34,4], index=["A","B","C","D"])
series1

A    10
B     2
C    34
D     4
dtype: int64

In [4]:
import pandas
series1 = pandas.Series([10,2,34,4], index=["A","B","C","D"]) # series with customize index
series1.to_dict() #convert hole series into dictionary

{'A': 10, 'B': 2, 'C': 34, 'D': 4}

In [15]:
arr1=np.array([10,13,15,19,24])
series1 = pd.Series(arr1)
print(series1)
print(type(series1))

0    10
1    13
2    15
3    19
4    24
dtype: int64
<class 'pandas.core.series.Series'>


In [17]:
arr1=np.array([10,13,15,19,24,10])
series1 = pd.Series(arr1)
print(series1)
print(series1.value_counts())

0    10
1    13
2    15
3    19
4    24
5    10
dtype: int64
10    2
13    1
15    1
19    1
24    1
Name: count, dtype: int64


In [20]:
arr1=np.array([10,13,15,19,24,10])
series1 = pd.Series(arr1)
print(series1.value_counts(ascending=True)) # ascending is false by default

13    1
15    1
19    1
24    1
10    2
Name: count, dtype: int64


In [21]:
arr1=np.array([10,13,15,19,24,10])
series1 = pd.Series(arr1)
series1.is_unique # Do we have unique elements or not

False

In [22]:
series1.nunique() # total unique elements

5

In [23]:
arr1=np.array([10,13,15,19,24,10])
series1 = pd.Series(arr1)
series1.sort_values()

0    10
5    10
1    13
2    15
3    19
4    24
dtype: int64

In [24]:
arr1=np.array([100,13,15,10,90,15])
series1=pd.Series(arr1)
print(series1)

0    100
1     13
2     15
3     10
4     90
5     15
dtype: int64


In [28]:
arr1=np.array([100,13,15,10,90,15])
series1=pd.Series(arr1)
series1.drop_duplicates() # Does not make any changes in original data

0    100
1     13
2     15
3     10
4     90
dtype: int64

In [31]:
arr1=np.array([100,13,15,10,90,15])
series1=pd.Series(arr1)
series1.drop_duplicates(inplace=True) # inplace = Make permanent change in original data
series1

0    100
1     13
2     15
3     10
4     90
dtype: int64

In [ ]:
import pandas as pd

data_dict = {
    'a': 10,
    'b': 20,
    'c': 30}

series = pd.Series(data_dict)

print(series)


a    10
b    20
c    30
dtype: int64


In [34]:
data=[[10,12,13],[13,14,15]]
df=pd.DataFrame(data,columns=["Product1","Product2","Product3"])
print(df)

   Product1  Product2  Product3
0        10        12        13
1        13        14        15


In [38]:
print(df["Product1"])
print("""
""")
print(type(df["Product1"]))

0    10
1    13
Name: Product1, dtype: int64


<class 'pandas.core.series.Series'>


In [ ]:
import csv

with open('movies.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)




['movieId', 'title', 'genres']
['1', 'Toy Story (1995)', 'Adventure|Animation|Children|Comedy|Fantasy']
['2', 'Jumanji (1995)', 'Adventure|Children|Fantasy']
['3', 'Grumpier Old Men (1995)', 'Comedy|Romance']
['4', 'Waiting to Exhale (1995)', 'Comedy|Drama|Romance']
['5', 'Father of the Bride Part II (1995)', 'Comedy']
['6', 'Heat (1995)', 'Action|Crime|Thriller']
['7', 'Sabrina (1995)', 'Comedy|Romance']
['8', 'Tom and Huck (1995)', 'Adventure|Children']
['9', 'Sudden Death (1995)', 'Action']
['10', 'GoldenEye (1995)', 'Action|Adventure|Thriller']
['11', 'American President, The (1995)', 'Comedy|Drama|Romance']
['12', 'Dracula: Dead and Loving It (1995)', 'Comedy|Horror']
['13', 'Balto (1995)', 'Adventure|Animation|Children']
['14', 'Nixon (1995)', 'Drama']
['15', 'Cutthroat Island (1995)', 'Action|Adventure|Romance']
['16', 'Casino (1995)', 'Crime|Drama']
['17', 'Sense and Sensibility (1995)', 'Drama|Romance']
['18', 'Four Rooms (1995)', 'Comedy']
['19', 'Ace Ventura: When Nature Cal

In [ ]:
import csv

with open('links.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


['movieId', 'imdbId', 'tmdbId']
['1', '0114709', '862']
['2', '0113497', '8844']
['3', '0113228', '15602']
['4', '0114885', '31357']
['5', '0113041', '11862']
['6', '0113277', '949']
['7', '0114319', '11860']
['8', '0112302', '45325']
['9', '0114576', '9091']
['10', '0113189', '710']
['11', '0112346', '9087']
['12', '0112896', '12110']
['13', '0112453', '21032']
['14', '0113987', '10858']
['15', '0112760', '1408']
['16', '0112641', '524']
['17', '0114388', '4584']
['18', '0113101', '5']
['19', '0112281', '9273']
['20', '0113845', '11517']
['21', '0113161', '8012']
['22', '0112722', '1710']
['23', '0112401', '9691']
['24', '0114168', '12665']
['25', '0113627', '451']
['26', '0114057', '16420']
['27', '0114011', '9263']
['28', '0114117', '17015']
['29', '0112682', '902']
['30', '0115012', '37557']
['31', '0112792', '9909']
['32', '0114746', '63']
['34', '0112431', '9598']
['36', '0112818', '687']
['38', '0113442', '33689']
['39', '0112697', '9603']
['40', '0112749', '34615']
['41', '0114

In [ ]:
import csv

with open('ratings.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)


Streaming output truncated to the last 5000 lines.
['600', '46664', '2.5', '1237742234']
['600', '46723', '2.5', '1237711558']
['600', '46967', '3.5', '1237763964']
['600', '46976', '4.0', '1237764337']
['600', '48082', '3.5', '1237714208']
['600', '48385', '4.5', '1237713658']
['600', '48394', '4.5', '1237764332']
['600', '48774', '4.0', '1237742695']
['600', '48783', '1.0', '1237760925']
['600', '49530', '1.0', '1237851408']
['600', '50658', '4.0', '1237708787']
['600', '50740', '4.0', '1237712734']
['600', '52435', '4.0', '1237857585']
['600', '52767', '4.0', '1237708647']
['600', '53024', '3.0', '1237712770']
['600', '53125', '4.0', '1237713628']
['600', '53322', '1.0', '1237851956']
['600', '53953', '2.0', '1237708566']
['600', '54286', '1.0', '1237851402']
['600', '55052', '1.5', '1237711199']
['600', '55247', '1.5', '1237760069']
['600', '55830', '4.0', '1237743114']
['600', '56775', '0.5', '1237760907']
['600', '58559', '3.5', '1237851393']
['600', '59131', '3.5', '1237710526']

In [ ]:
import csv

df=pd.read_csv("links.csv")
print(df)

col= df['movieId']
print("""
""")
counts = col.value_counts()
print(counts)
print("""
""")
unique_counts=col.nunique()
print(unique_counts)
print("""

""")
dupli = col.drop_duplicates()
print(dupli)
print("""

""")
df['movieId'] = df['movieId'].astype(float)
print( df['movieId'].head(3))



      movieId   imdbId    tmdbId
0           1   114709     862.0
1           2   113497    8844.0
2           3   113228   15602.0
3           4   114885   31357.0
4           5   113041   11862.0
...       ...      ...       ...
9737   193581  5476944  432131.0
9738   193583  5914996  445030.0
9739   193585  6397426  479308.0
9740   193587  8391976  483455.0
9741   193609   101726   37891.0

[9742 rows x 3 columns]


movieId
193609    1
1         1
2         1
3         1
4         1
         ..
19        1
18        1
17        1
16        1
15        1
Name: count, Length: 9742, dtype: int64


9742



0            1
1            2
2            3
3            4
4            5
         ...  
9737    193581
9738    193583
9739    193585
9740    193587
9741    193609
Name: movieId, Length: 9742, dtype: int64



0    1.0
1    2.0
2    3.0
Name: movieId, dtype: float64
